# Postgresql Database
spring.datasource.url=jdbc:postgresql://dpg-d8l430kvikkc73ccfgk0-a.singapore-postgres.render.com/fintrack_qv4h
spring.datasource.username=fintrack_qv4h_user
spring.datasource.password=bEhRKtk1QR9VJAFbwLbezL1WTjdMGXUS